version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/pipecat_smart_turn"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/pipecat_smart_turn/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/pipecat_smart_turn_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/pipecat_smart_turn_android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/pipecat_smart_turn_ios"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/pipecat_smart_turn_linux"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/pipecat_smart_turn_macos"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/pipecat_smart_turn_web"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/pipecat_smart_turn_windows"
    schedule:
      interval: "daily"