name: pipecat_smart_turn
description: Pipecat Smart Turn Flutter package
version: 0.1.0+1
publish_to: none


environment:
  sdk: ^3.11.0

flutter:
  # No plugin block needed as logic is moved to platform_interface.

dependencies:
  flutter:
    sdk: flutter
  pipecat_smart_turn_platform_interface:
    path: ../pipecat_smart_turn_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0
