name: pipecat_smart_turn
description: Pipecat Smart Turn Flutter package
version: 0.1.0+1


environment:
  sdk: ^3.11.0

flutter:
  plugin:
    platforms:
      android:
        default_package: pipecat_smart_turn_android
      ios:
        default_package: pipecat_smart_turn_ios
      linux:
        default_package: pipecat_smart_turn_linux
      macos:
        default_package: pipecat_smart_turn_macos
      web:
        default_package: pipecat_smart_turn_web
      windows:
        default_package: pipecat_smart_turn_windows

dependencies:
  flutter:
    sdk: flutter
  pipecat_smart_turn_android:
    path: ../pipecat_smart_turn_android
  pipecat_smart_turn_ios:
    path: ../pipecat_smart_turn_ios
  pipecat_smart_turn_linux:
    path: ../pipecat_smart_turn_linux
  pipecat_smart_turn_macos:
    path: ../pipecat_smart_turn_macos
  pipecat_smart_turn_platform_interface:
    path: ../pipecat_smart_turn_platform_interface
  pipecat_smart_turn_web:
    path: ../pipecat_smart_turn_web
  pipecat_smart_turn_windows:
    path: ../pipecat_smart_turn_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.2.0
