name: pipecat_smart_turn_platform_interface

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/pipecat_smart_turn_platform_interface.yaml"
      - "pipecat_smart_turn_platform_interface/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/pipecat_smart_turn_platform_interface.yaml"
      - "pipecat_smart_turn_platform_interface/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_version: 3.41.1
      working_directory: pipecat_smart_turn_platform_interface

  pana:
    uses: ./.github/workflows/pana.yaml
    with:
      working_directory: pipecat_smart_turn_platform_interface

