name: pipecat_smart_turn_linux

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/pipecat_smart_turn_linux.yaml"
      - "pipecat_smart_turn_linux/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/pipecat_smart_turn_linux.yaml"
      - "pipecat_smart_turn_linux/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_version: 3.41.1
      working_directory: pipecat_smart_turn_linux

  pana:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1

